language: php
sudo: false

env:
  - SYMFONY_VERSION=2.8.*

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: hhvm
    - php: nightly
  allow_failures:
    - php: hhvm

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install:
  - composer update --prefer-source $COMPOSER_FLAGS

script:
  - phpunit -c app

cache:
  directories:
    - $HOME/.composer/cache/files

notifications:
  slack: mlankatech:R6kNSDaAslgbB9rf0PjXxnhu
